#!/bin/sh


PACKAGE_NAME=yaroot-game-davies
BIN_DIR=/usr/share/yaroot/$PACKAGE_NAME

chmod 0600 $BIN_DIR/05_mail/amu_key
chown www-data:www-data $BIN_DIR/05_mail/amu_key

chmod 0600 $BIN_DIR/06_twmail/amu_key
chown www-data:www-data $BIN_DIR/06_twmail/amu_key
