#!/bin/sh

#update-ca-certificates

PACKAGE_NAME=yaroot-game-postel
BIN_DIR=/usr/share/yaroot/$PACKAGE_NAME

name=dpkt-1.6 tmp=$(mktemp -d)
tar -C "$tmp" -x -f "$BIN_DIR/netflow/${name}.tar"
make -C "$tmp/$name"
make -C "$tmp/$name" install
rm -rf "$tmp"

chmod 0600 $BIN_DIR/ci/id_rsa
chown www-data:www-data $BIN_DIR/ci/id_rsa
